openapi: 3.0.0
info:
  title: Todo API
  description: API para gerenciar tarefas (Todos)
  version: 1.0.0
  contact:
    name: Cesar Menegatti
    email: cesar.menegatti@outlook.com.br
servers:
  - url: http://localhost:8080
tags:
  - name: todos
    description: Operações relacionadas a todos
paths:
  /todos:
    get:
      tags:
        - todos
      summary: Retorna todos os todos
      operationId: getAllTodos
      description: Retorna uma lista com todos os todos cadastrados
      responses:
        '200':
          description: Lista de todos os todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Cria um novo todo
      tags:
        - todos
      operationId: createTodo
      description: Cria um novo todo com base nos dados informados
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          description: Todo criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /todos/{id}:
    get:
      tags:
        - todos
      summary: Retorna um todo pelo ID
      operationId: getTodoById
      description: Retorna um todo com base no ID informado
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Todo retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo não encontrado
    put:
      tags:
        - todos
      summary: Atualiza um todo pelo ID
      operationId: updateTodo
      description: Atualiza um todo com base no ID informado e nos dados informados
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Todo atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo não encontrado
    delete:
      summary: Deleta um todo pelo ID
      operationId: deleteTodo
      tags:
          - todos
      description: Deleta um todo com base no ID informado
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Todo deletado com sucesso
        '404':
          description: Todo não encontrado
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          description: ID do todo
        title:
          type: string
          description: Título do todo
        description:
          type: string
          description: Descrição do todo
        completed:
          type: boolean
          description: Indica se o todo foi concluído
      required:
        - title
        - description
        - completed
